from typing import Any, Protocol, Self


class MLModel(Protocol):
    def fit(self, X: Any, y: Any) -> Self: ...
    def predict(self, X: Any) -> Any: ...
    def partial_fit(self, X: Any, y: Any) -> Self: ...
