exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "docs",
]
source_roots = [
    ".",
]
use_regex_matching = false

[[modules]]
path = "<root>"
depends_on = [
    "app",
    "app.auth",
    "app.auth.provider.github",
    "app.auth.provider.google",
    "app.auth.provider.gumroad",
    "app.controllers",
    "app.data",
    "app.injections",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app"
depends_on = [
    "app.api.router",
    "app.auth",
    "app.injections",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.api.router"
depends_on = [
    "app",
    "app.api.router.provider",
    "app.auth",
    "app.controllers",
    "app.models",
]

[[modules]]
path = "app.api.router.provider"
depends_on = [
    "app",
    "app.auth",
]

[[modules]]
path = "app.auth"
depends_on = [
    "app.auth.provider.github",
    "app.auth.provider.google",
    "app.auth.provider.gumroad",
    "app.controllers",
    "app.models",
]

[[modules]]
path = "app.auth.provider.github"
depends_on = [
    "app.auth",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.auth.provider.google"
depends_on = [
    "app.auth",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.auth.provider.gumroad"
depends_on = [
    "app.auth",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.controllers"
depends_on = [
    "app.data",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.data"
depends_on = [
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.injections"
depends_on = [
    "app.auth",
    "app.controllers",
    "app.data",
    "app.models",
    "app.settings",
]

[[modules]]
path = "app.models"
depends_on = []

[[modules]]
path = "app.settings"
depends_on = []

[[modules]]
path = "app.views"
depends_on = []

[[interfaces]]
expose = [
    "EXCEPTION_HANDLERS",
    "routers",
]
from = [
    "app.api.router",
]

[[interfaces]]
expose = []
from = [
    "app.api.router.provider",
]

[[interfaces]]
expose = [
    "GithubUser",
    "GithubUserEmail",
    "GithubUserEmails",
    "get_user_from_provider",
    "oauth_config",
]
from = [
    "app.auth.provider.github",
]

[[interfaces]]
expose = [
    "GoogleUser",
    "get_user_from_provider",
    "oauth_config",
]
from = [
    "app.auth.provider.google",
]

[[interfaces]]
expose = [
    "GumroadUser",
    "GumroadUserResponse",
    "get_user_from_provider",
    "oauth_config",
]
from = [
    "app.auth.provider.gumroad",
]

[[interfaces]]
expose = [
    "PROVIDER_ROUTERS",
]
from = [
    "app.api.router.provider",
]
